/*
See LICENSE file in root folder
*/
#include "ShaderAST/Expr/ExprCombinedImageAccessCall.hpp"

#include "ShaderAST/Expr/ExprVisitor.hpp"
#include "ShaderAST/Expr/EnumSampledImageAccess.hpp"

namespace ast::expr
{
	//*********************************************************************************************

	CombinedImageAccessCall::CombinedImageAccessCall( type::TypePtr type
		, CombinedImageAccess textureAccess
		, ExprList && argList )
		: Expr{ getExprTypesCache( argList ), std::move( type ), Kind::eCombinedImageAccessCall, Flag::eNone }
		, m_textureAccess{ textureAccess }
		, m_argList{ std::move( argList ) }
	{
	}

	void CombinedImageAccessCall::accept( VisitorPtr vis )
	{
		vis->visitCombinedImageAccessCallExpr( this );
	}

	//*********************************************************************************************

	bool isBiasAndOffset( CombinedImageAccess value )
	{
		switch ( value )
		{
		case CombinedImageAccess::eTextureOffset1DFBias:
		case CombinedImageAccess::eTextureOffset2DFBias:
		case CombinedImageAccess::eTextureOffset3DFBias:
		case CombinedImageAccess::eTextureOffset1DArrayFBias:
		case CombinedImageAccess::eTextureOffset2DArrayFBias:
		case CombinedImageAccess::eTextureOffset1DIBias:
		case CombinedImageAccess::eTextureOffset2DIBias:
		case CombinedImageAccess::eTextureOffset3DIBias:
		case CombinedImageAccess::eTextureOffset1DArrayIBias:
		case CombinedImageAccess::eTextureOffset2DArrayIBias:
		case CombinedImageAccess::eTextureOffset1DUBias:
		case CombinedImageAccess::eTextureOffset2DUBias:
		case CombinedImageAccess::eTextureOffset3DUBias:
		case CombinedImageAccess::eTextureOffset1DArrayUBias:
		case CombinedImageAccess::eTextureOffset2DArrayUBias:
		case CombinedImageAccess::eTextureProjOffset1DF2Bias:
		case CombinedImageAccess::eTextureProjOffset1DF4Bias:
		case CombinedImageAccess::eTextureProjOffset2DF3Bias:
		case CombinedImageAccess::eTextureProjOffset2DF4Bias:
		case CombinedImageAccess::eTextureProjOffset3DFBias:
		case CombinedImageAccess::eTextureProjOffset1DI2Bias:
		case CombinedImageAccess::eTextureProjOffset1DI4Bias:
		case CombinedImageAccess::eTextureProjOffset2DI3Bias:
		case CombinedImageAccess::eTextureProjOffset2DI4Bias:
		case CombinedImageAccess::eTextureProjOffset3DIBias:
		case CombinedImageAccess::eTextureProjOffset1DU2Bias:
		case CombinedImageAccess::eTextureProjOffset1DU4Bias:
		case CombinedImageAccess::eTextureProjOffset2DU3Bias:
		case CombinedImageAccess::eTextureProjOffset2DU4Bias:
		case CombinedImageAccess::eTextureProjOffset3DUBias:
			return true;
		default:
			return false;
		}
	}

	bool isProj( ast::expr::CombinedImageAccess value )
	{
		switch ( value )
		{
		case ast::expr::CombinedImageAccess::eTextureProj1DF2:
		case ast::expr::CombinedImageAccess::eTextureProj1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProj1DI2:
		case ast::expr::CombinedImageAccess::eTextureProj1DU2:
		case ast::expr::CombinedImageAccess::eTextureProj1DF2Bias:
		case ast::expr::CombinedImageAccess::eTextureProj1DShadowFBias:
		case ast::expr::CombinedImageAccess::eTextureProj1DI2Bias:
		case ast::expr::CombinedImageAccess::eTextureProj1DU2Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DF2:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DI2:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DU2:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DF2Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DShadowFBias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DI2Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DU2Bias:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DF2:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DI2:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DU2:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DF2:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DI2:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DU2:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DF2:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DI2:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DU2:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DF2:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DI2:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DU2:
		case ast::expr::CombinedImageAccess::eTextureProj1DF4:
		case ast::expr::CombinedImageAccess::eTextureProj1DI4:
		case ast::expr::CombinedImageAccess::eTextureProj1DU4:
		case ast::expr::CombinedImageAccess::eTextureProj1DF4Bias:
		case ast::expr::CombinedImageAccess::eTextureProj1DI4Bias:
		case ast::expr::CombinedImageAccess::eTextureProj1DU4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DF4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DI4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DU4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DF4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DI4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset1DU4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DF4:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DI4:
		case ast::expr::CombinedImageAccess::eTextureProjLod1DU4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DF4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DI4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset1DU4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DF4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DI4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad1DU4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DF4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DI4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset1DU4:
		case ast::expr::CombinedImageAccess::eTextureProj2DF3:
		case ast::expr::CombinedImageAccess::eTextureProj2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectF3:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectShadowF:
		case ast::expr::CombinedImageAccess::eTextureProj2DI3:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectI3:
		case ast::expr::CombinedImageAccess::eTextureProj2DU3:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectU3:
		case ast::expr::CombinedImageAccess::eTextureProj2DF3Bias:
		case ast::expr::CombinedImageAccess::eTextureProj2DShadowFBias:
		case ast::expr::CombinedImageAccess::eTextureProj2DI3Bias:
		case ast::expr::CombinedImageAccess::eTextureProj2DU3Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DF3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectF3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DI3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectI3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DU3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectU3:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DF3Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DShadowFBias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DI3Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DU3Bias:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DF3:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DI3:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DU3:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DF3:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DI3:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DU3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DF3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectF3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DI3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectI3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DU3:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectU3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DF3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectF3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectShadowF:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DI3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectI3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DU3:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectU3:
		case ast::expr::CombinedImageAccess::eTextureProj2DF4:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectF4:
		case ast::expr::CombinedImageAccess::eTextureProj2DI4:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectI4:
		case ast::expr::CombinedImageAccess::eTextureProj2DU4:
		case ast::expr::CombinedImageAccess::eTextureProj2DRectU4:
		case ast::expr::CombinedImageAccess::eTextureProj2DF4Bias:
		case ast::expr::CombinedImageAccess::eTextureProj2DI4Bias:
		case ast::expr::CombinedImageAccess::eTextureProj2DU4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DF4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectF4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DI4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectI4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DU4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DRectU4:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DF4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DI4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset2DU4Bias:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DF4:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DI4:
		case ast::expr::CombinedImageAccess::eTextureProjLod2DU4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DF4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DI4:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset2DU4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DF4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectF4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DI4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectI4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DU4:
		case ast::expr::CombinedImageAccess::eTextureProjGrad2DRectU4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DF4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectF4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DI4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectI4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DU4:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset2DRectU4:
		case ast::expr::CombinedImageAccess::eTextureProj3DF:
		case ast::expr::CombinedImageAccess::eTextureProj3DI:
		case ast::expr::CombinedImageAccess::eTextureProj3DU:
		case ast::expr::CombinedImageAccess::eTextureProj3DFBias:
		case ast::expr::CombinedImageAccess::eTextureProj3DIBias:
		case ast::expr::CombinedImageAccess::eTextureProj3DUBias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DF:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DI:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DU:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DFBias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DIBias:
		case ast::expr::CombinedImageAccess::eTextureProjOffset3DUBias:
		case ast::expr::CombinedImageAccess::eTextureProjLod3DF:
		case ast::expr::CombinedImageAccess::eTextureProjLod3DI:
		case ast::expr::CombinedImageAccess::eTextureProjLod3DU:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset3DF:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset3DI:
		case ast::expr::CombinedImageAccess::eTextureProjLodOffset3DU:
		case ast::expr::CombinedImageAccess::eTextureProjGrad3DF:
		case ast::expr::CombinedImageAccess::eTextureProjGrad3DI:
		case ast::expr::CombinedImageAccess::eTextureProjGrad3DU:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset3DF:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset3DI:
		case ast::expr::CombinedImageAccess::eTextureProjGradOffset3DU:
			return true;
		default:
			return false;
		}
	}

	bool isShadow( CombinedImageAccess value )
	{
		switch ( value )
		{
		case CombinedImageAccess::eTexture1DShadowF:
		case CombinedImageAccess::eTexture1DShadowFBias:
		case CombinedImageAccess::eTexture2DShadowF:
		case CombinedImageAccess::eTexture2DShadowFBias:
		case CombinedImageAccess::eTextureCubeShadowF:
		case CombinedImageAccess::eTextureCubeShadowFBias:
		case CombinedImageAccess::eTexture1DArrayShadowF:
		case CombinedImageAccess::eTexture1DArrayShadowFBias:
		case CombinedImageAccess::eTexture2DArrayShadowF:
		case CombinedImageAccess::eTexture2DRectShadowF:
		case CombinedImageAccess::eTextureCubeArrayShadowF:
		case CombinedImageAccess::eTextureProj1DShadowF:
		case CombinedImageAccess::eTextureProj1DShadowFBias:
		case CombinedImageAccess::eTextureProj2DShadowF:
		case CombinedImageAccess::eTextureProj2DShadowFBias:
		case CombinedImageAccess::eTextureProj2DRectShadowF:
		case CombinedImageAccess::eTextureLod1DShadowF:
		case CombinedImageAccess::eTextureLod2DShadowF:
		case CombinedImageAccess::eTextureLod1DArrayShadowF:
		case CombinedImageAccess::eTextureOffset2DRectShadowF:
		case CombinedImageAccess::eTextureOffset1DShadowF:
		case CombinedImageAccess::eTextureOffset1DShadowFBias:
		case CombinedImageAccess::eTextureOffset2DShadowF:
		case CombinedImageAccess::eTextureOffset2DShadowFBias:
		case CombinedImageAccess::eTextureOffset1DArrayShadowF:
		case CombinedImageAccess::eTextureOffset2DArrayShadowF:
		case CombinedImageAccess::eTextureProjOffset1DShadowF:
		case CombinedImageAccess::eTextureProjOffset1DShadowFBias:
		case CombinedImageAccess::eTextureProjOffset2DShadowF:
		case CombinedImageAccess::eTextureProjOffset2DShadowFBias:
		case CombinedImageAccess::eTextureProjOffset2DRectShadowF:
		case CombinedImageAccess::eTextureLodOffset1DShadowF:
		case CombinedImageAccess::eTextureLodOffset2DShadowF:
		case CombinedImageAccess::eTextureLodOffset1DArrayShadowF:
		case CombinedImageAccess::eTextureProjLod1DShadowF:
		case CombinedImageAccess::eTextureProjLod2DShadowF:
		case CombinedImageAccess::eTextureProjLodOffset1DShadowF:
		case CombinedImageAccess::eTextureProjLodOffset2DShadowF:
		case CombinedImageAccess::eTextureGrad2DRectShadowF:
		case CombinedImageAccess::eTextureGrad1DShadowF:
		case CombinedImageAccess::eTextureGrad2DShadowF:
		case CombinedImageAccess::eTextureGrad1DArrayShadowF:
		case CombinedImageAccess::eTextureGradOffset2DRectShadowF:
		case CombinedImageAccess::eTextureGradOffset1DShadowF:
		case CombinedImageAccess::eTextureGradOffset2DShadowF:
		case CombinedImageAccess::eTextureGradOffset1DArrayShadowF:
		case CombinedImageAccess::eTextureGradOffset2DArrayShadowF:
		case CombinedImageAccess::eTextureProjGrad1DShadowF:
		case CombinedImageAccess::eTextureProjGrad2DShadowF:
		case CombinedImageAccess::eTextureProjGrad2DRectShadowF:
		case CombinedImageAccess::eTextureProjGradOffset1DShadowF:
		case CombinedImageAccess::eTextureProjGradOffset2DShadowF:
		case CombinedImageAccess::eTextureProjGradOffset2DRectShadowF:
		case CombinedImageAccess::eTextureGather2DShadowF:
		case CombinedImageAccess::eTextureGather2DArrayShadowF:
		case CombinedImageAccess::eTextureGatherCubeShadowF:
		case CombinedImageAccess::eTextureGatherCubeArrayShadowF:
		case CombinedImageAccess::eTextureGather2DRectShadowF:
		case CombinedImageAccess::eTextureGatherOffset2DShadowF:
		case CombinedImageAccess::eTextureGatherOffset2DArrayShadowF:
		case CombinedImageAccess::eTextureGatherOffset2DRectShadowF:
		case CombinedImageAccess::eTextureGatherOffsets2DShadowF:
		case CombinedImageAccess::eTextureGatherOffsets2DArrayShadowF:
		case CombinedImageAccess::eTextureGatherOffsets2DRectShadowF:
			return true;
		default:
			return false;
		}
	}

	bool isShadowLodOffset( CombinedImageAccess value )
	{
		switch ( value )
		{
		case CombinedImageAccess::eTextureLodOffset1DShadowF:
		case CombinedImageAccess::eTextureLodOffset2DShadowF:
		case CombinedImageAccess::eTextureLodOffset1DArrayShadowF:
		case CombinedImageAccess::eTextureProjLodOffset1DShadowF:
		case CombinedImageAccess::eTextureProjLodOffset2DShadowF:
			return true;
		default:
			return false;
		}
	}

	CombinedImageAccess convert( SampledImageAccess value )
	{
		switch ( value )
		{
		case SampledImageAccess::eUndefined:
			return CombinedImageAccess::eUndefined;
		case SampledImageAccess::eSample1DF:
			return CombinedImageAccess::eTexture1DF;
		case SampledImageAccess::eSample1DFBias:
			return CombinedImageAccess::eTexture1DFBias;
		case SampledImageAccess::eSample2DF:
			return CombinedImageAccess::eTexture2DF;
		case SampledImageAccess::eSample2DFBias:
			return CombinedImageAccess::eTexture2DFBias;
		case SampledImageAccess::eSample3DF:
			return CombinedImageAccess::eTexture3DF;
		case SampledImageAccess::eSample3DFBias:
			return CombinedImageAccess::eTexture3DFBias;
		case SampledImageAccess::eSampleCubeF:
			return CombinedImageAccess::eTextureCubeF;
		case SampledImageAccess::eSampleCubeFBias:
			return CombinedImageAccess::eTextureCubeFBias;
		case SampledImageAccess::eSample1DArrayF:
			return CombinedImageAccess::eTexture1DArrayF;
		case SampledImageAccess::eSample1DArrayFBias:
			return CombinedImageAccess::eTexture1DArrayFBias;
		case SampledImageAccess::eSample2DArrayF:
			return CombinedImageAccess::eTexture2DArrayF;
		case SampledImageAccess::eSample2DArrayFBias:
			return CombinedImageAccess::eTexture2DArrayFBias;
		case SampledImageAccess::eSampleCubeArrayF:
			return CombinedImageAccess::eTextureCubeArrayF;
		case SampledImageAccess::eSampleCubeArrayFBias:
			return CombinedImageAccess::eTextureCubeArrayFBias;
		case SampledImageAccess::eSample2DRectF:
			return CombinedImageAccess::eTexture2DRectF;
		case SampledImageAccess::eSample1DI:
			return CombinedImageAccess::eTexture1DI;
		case SampledImageAccess::eSample1DIBias:
			return CombinedImageAccess::eTexture1DIBias;
		case SampledImageAccess::eSample2DI:
			return CombinedImageAccess::eTexture2DI;
		case SampledImageAccess::eSample2DIBias:
			return CombinedImageAccess::eTexture2DIBias;
		case SampledImageAccess::eSample3DI:
			return CombinedImageAccess::eTexture3DI;
		case SampledImageAccess::eSample3DIBias:
			return CombinedImageAccess::eTexture3DIBias;
		case SampledImageAccess::eSampleCubeI:
			return CombinedImageAccess::eTextureCubeI;
		case SampledImageAccess::eSampleCubeIBias:
			return CombinedImageAccess::eTextureCubeIBias;
		case SampledImageAccess::eSample1DArrayI:
			return CombinedImageAccess::eTexture1DArrayI;
		case SampledImageAccess::eSample1DArrayIBias:
			return CombinedImageAccess::eTexture1DArrayIBias;
		case SampledImageAccess::eSample2DArrayI:
			return CombinedImageAccess::eTexture2DArrayI;
		case SampledImageAccess::eSample2DArrayIBias:
			return CombinedImageAccess::eTexture2DArrayIBias;
		case SampledImageAccess::eSampleCubeArrayI:
			return CombinedImageAccess::eTextureCubeArrayI;
		case SampledImageAccess::eSampleCubeArrayIBias:
			return CombinedImageAccess::eTextureCubeArrayIBias;
		case SampledImageAccess::eSample2DRectI:
			return CombinedImageAccess::eTexture2DRectI;
		case SampledImageAccess::eSample1DU:
			return CombinedImageAccess::eTexture1DU;
		case SampledImageAccess::eSample1DUBias:
			return CombinedImageAccess::eTexture1DUBias;
		case SampledImageAccess::eSample2DU:
			return CombinedImageAccess::eTexture2DU;
		case SampledImageAccess::eSample2DUBias:
			return CombinedImageAccess::eTexture2DUBias;
		case SampledImageAccess::eSample3DU:
			return CombinedImageAccess::eTexture3DU;
		case SampledImageAccess::eSample3DUBias:
			return CombinedImageAccess::eTexture3DUBias;
		case SampledImageAccess::eSampleCubeU:
			return CombinedImageAccess::eTextureCubeU;
		case SampledImageAccess::eSampleCubeUBias:
			return CombinedImageAccess::eTextureCubeUBias;
		case SampledImageAccess::eSample1DArrayU:
			return CombinedImageAccess::eTexture1DArrayU;
		case SampledImageAccess::eSample1DArrayUBias:
			return CombinedImageAccess::eTexture1DArrayUBias;
		case SampledImageAccess::eSample2DArrayU:
			return CombinedImageAccess::eTexture2DArrayU;
		case SampledImageAccess::eSample2DArrayUBias:
			return CombinedImageAccess::eTexture2DArrayUBias;
		case SampledImageAccess::eSampleCubeArrayU:
			return CombinedImageAccess::eTextureCubeArrayU;
		case SampledImageAccess::eSampleCubeArrayUBias:
			return CombinedImageAccess::eTextureCubeArrayUBias;
		case SampledImageAccess::eSample2DRectU:
			return CombinedImageAccess::eTexture2DRectU;
		case SampledImageAccess::eSampleProj1DF2:
			return CombinedImageAccess::eTextureProj1DF2;
		case SampledImageAccess::eSampleProj1DF2Bias:
			return CombinedImageAccess::eTextureProj1DF2Bias;
		case SampledImageAccess::eSampleProj1DF4:
			return CombinedImageAccess::eTextureProj1DF4;
		case SampledImageAccess::eSampleProj1DF4Bias:
			return CombinedImageAccess::eTextureProj1DF4Bias;
		case SampledImageAccess::eSampleProj2DF3:
			return CombinedImageAccess::eTextureProj2DF3;
		case SampledImageAccess::eSampleProj2DF3Bias:
			return CombinedImageAccess::eTextureProj2DF3Bias;
		case SampledImageAccess::eSampleProj2DF4:
			return CombinedImageAccess::eTextureProj2DF4;
		case SampledImageAccess::eSampleProj2DF4Bias:
			return CombinedImageAccess::eTextureProj2DF4Bias;
		case SampledImageAccess::eSampleProj3DF:
			return CombinedImageAccess::eTextureProj3DF;
		case SampledImageAccess::eSampleProj3DFBias:
			return CombinedImageAccess::eTextureProj3DFBias;
		case SampledImageAccess::eSampleProj2DRectF3:
			return CombinedImageAccess::eTextureProj2DRectF3;
		case SampledImageAccess::eSampleProj2DRectF4:
			return CombinedImageAccess::eTextureProj2DRectF4;
		case SampledImageAccess::eSampleProj1DI2:
			return CombinedImageAccess::eTextureProj1DI2;
		case SampledImageAccess::eSampleProj1DI2Bias:
			return CombinedImageAccess::eTextureProj1DI2Bias;
		case SampledImageAccess::eSampleProj1DI4:
			return CombinedImageAccess::eTextureProj1DI4;
		case SampledImageAccess::eSampleProj1DI4Bias:
			return CombinedImageAccess::eTextureProj1DI4Bias;
		case SampledImageAccess::eSampleProj2DI3:
			return CombinedImageAccess::eTextureProj2DI3;
		case SampledImageAccess::eSampleProj2DI3Bias:
			return CombinedImageAccess::eTextureProj2DI3Bias;
		case SampledImageAccess::eSampleProj2DI4:
			return CombinedImageAccess::eTextureProj2DI4;
		case SampledImageAccess::eSampleProj2DI4Bias:
			return CombinedImageAccess::eTextureProj2DI4Bias;
		case SampledImageAccess::eSampleProj3DI:
			return CombinedImageAccess::eTextureProj3DI;
		case SampledImageAccess::eSampleProj3DIBias:
			return CombinedImageAccess::eTextureProj3DIBias;
		case SampledImageAccess::eSampleProj2DRectI3:
			return CombinedImageAccess::eTextureProj2DRectI3;
		case SampledImageAccess::eSampleProj2DRectI4:
			return CombinedImageAccess::eTextureProj2DRectI4;
		case SampledImageAccess::eSampleProj1DU2:
			return CombinedImageAccess::eTextureProj1DU2;
		case SampledImageAccess::eSampleProj1DU2Bias:
			return CombinedImageAccess::eTextureProj1DU2Bias;
		case SampledImageAccess::eSampleProj1DU4:
			return CombinedImageAccess::eTextureProj1DU4;
		case SampledImageAccess::eSampleProj1DU4Bias:
			return CombinedImageAccess::eTextureProj1DU4Bias;
		case SampledImageAccess::eSampleProj2DU3:
			return CombinedImageAccess::eTextureProj2DU3;
		case SampledImageAccess::eSampleProj2DU3Bias:
			return CombinedImageAccess::eTextureProj2DU3Bias;
		case SampledImageAccess::eSampleProj2DU4:
			return CombinedImageAccess::eTextureProj2DU4;
		case SampledImageAccess::eSampleProj2DU4Bias:
			return CombinedImageAccess::eTextureProj2DU4Bias;
		case SampledImageAccess::eSampleProj3DU:
			return CombinedImageAccess::eTextureProj3DU;
		case SampledImageAccess::eSampleProj3DUBias:
			return CombinedImageAccess::eTextureProj3DUBias;
		case SampledImageAccess::eSampleProj2DRectU3:
			return CombinedImageAccess::eTextureProj2DRectU3;
		case SampledImageAccess::eSampleProj2DRectU4:
			return CombinedImageAccess::eTextureProj2DRectU4;
		case SampledImageAccess::eSampleLod1DF:
			return CombinedImageAccess::eTextureLod1DF;
		case SampledImageAccess::eSampleLod2DF:
			return CombinedImageAccess::eTextureLod2DF;
		case SampledImageAccess::eSampleLod3DF:
			return CombinedImageAccess::eTextureLod3DF;
		case SampledImageAccess::eSampleLodCubeF:
			return CombinedImageAccess::eTextureLodCubeF;
		case SampledImageAccess::eSampleLod1DArrayF:
			return CombinedImageAccess::eTextureLod1DArrayF;
		case SampledImageAccess::eSampleLod2DArrayF:
			return CombinedImageAccess::eTextureLod2DArrayF;
		case SampledImageAccess::eSampleLodCubeArrayF:
			return CombinedImageAccess::eTextureLodCubeArrayF;
		case SampledImageAccess::eSampleLod1DI:
			return CombinedImageAccess::eTextureLod1DI;
		case SampledImageAccess::eSampleLod2DI:
			return CombinedImageAccess::eTextureLod2DI;
		case SampledImageAccess::eSampleLod3DI:
			return CombinedImageAccess::eTextureLod3DI;
		case SampledImageAccess::eSampleLodCubeI:
			return CombinedImageAccess::eTextureLodCubeI;
		case SampledImageAccess::eSampleLod1DArrayI:
			return CombinedImageAccess::eTextureLod1DArrayI;
		case SampledImageAccess::eSampleLod2DArrayI:
			return CombinedImageAccess::eTextureLod2DArrayI;
		case SampledImageAccess::eSampleLodCubeArrayI:
			return CombinedImageAccess::eTextureLodCubeArrayI;
		case SampledImageAccess::eSampleLod1DU:
			return CombinedImageAccess::eTextureLod1DU;
		case SampledImageAccess::eSampleLod2DU:
			return CombinedImageAccess::eTextureLod2DU;
		case SampledImageAccess::eSampleLod3DU:
			return CombinedImageAccess::eTextureLod3DU;
		case SampledImageAccess::eSampleLodCubeU:
			return CombinedImageAccess::eTextureLodCubeU;
		case SampledImageAccess::eSampleLod1DArrayU:
			return CombinedImageAccess::eTextureLod1DArrayU;
		case SampledImageAccess::eSampleLod2DArrayU:
			return CombinedImageAccess::eTextureLod2DArrayU;
		case SampledImageAccess::eSampleLodCubeArrayU:
			return CombinedImageAccess::eTextureLodCubeArrayU;
		case SampledImageAccess::eSampleOffset1DF:
			return CombinedImageAccess::eTextureOffset1DF;
		case SampledImageAccess::eSampleOffset1DFBias:
			return CombinedImageAccess::eTextureOffset1DFBias;
		case SampledImageAccess::eSampleOffset2DF:
			return CombinedImageAccess::eTextureOffset2DF;
		case SampledImageAccess::eSampleOffset2DFBias:
			return CombinedImageAccess::eTextureOffset2DFBias;
		case SampledImageAccess::eSampleOffset3DF:
			return CombinedImageAccess::eTextureOffset3DF;
		case SampledImageAccess::eSampleOffset3DFBias:
			return CombinedImageAccess::eTextureOffset3DFBias;
		case SampledImageAccess::eSampleOffset2DRectF:
			return CombinedImageAccess::eTextureOffset2DRectF;
		case SampledImageAccess::eSampleOffset1DArrayF:
			return CombinedImageAccess::eTextureOffset1DArrayF;
		case SampledImageAccess::eSampleOffset1DArrayFBias:
			return CombinedImageAccess::eTextureOffset1DArrayFBias;
		case SampledImageAccess::eSampleOffset2DArrayF:
			return CombinedImageAccess::eTextureOffset2DArrayF;
		case SampledImageAccess::eSampleOffset2DArrayFBias:
			return CombinedImageAccess::eTextureOffset2DArrayFBias;
		case SampledImageAccess::eSampleOffset1DI:
			return CombinedImageAccess::eTextureOffset1DI;
		case SampledImageAccess::eSampleOffset1DIBias:
			return CombinedImageAccess::eTextureOffset1DIBias;
		case SampledImageAccess::eSampleOffset2DI:
			return CombinedImageAccess::eTextureOffset2DI;
		case SampledImageAccess::eSampleOffset2DIBias:
			return CombinedImageAccess::eTextureOffset2DIBias;
		case SampledImageAccess::eSampleOffset3DI:
			return CombinedImageAccess::eTextureOffset3DI;
		case SampledImageAccess::eSampleOffset3DIBias:
			return CombinedImageAccess::eTextureOffset3DIBias;
		case SampledImageAccess::eSampleOffset2DRectI:
			return CombinedImageAccess::eTextureOffset2DRectI;
		case SampledImageAccess::eSampleOffset1DArrayI:
			return CombinedImageAccess::eTextureOffset1DArrayI;
		case SampledImageAccess::eSampleOffset1DArrayIBias:
			return CombinedImageAccess::eTextureOffset1DArrayIBias;
		case SampledImageAccess::eSampleOffset2DArrayI:
			return CombinedImageAccess::eTextureOffset2DArrayI;
		case SampledImageAccess::eSampleOffset2DArrayIBias:
			return CombinedImageAccess::eTextureOffset2DArrayIBias;
		case SampledImageAccess::eSampleOffset1DU:
			return CombinedImageAccess::eTextureOffset1DU;
		case SampledImageAccess::eSampleOffset1DUBias:
			return CombinedImageAccess::eTextureOffset1DUBias;
		case SampledImageAccess::eSampleOffset2DU:
			return CombinedImageAccess::eTextureOffset2DU;
		case SampledImageAccess::eSampleOffset2DUBias:
			return CombinedImageAccess::eTextureOffset2DUBias;
		case SampledImageAccess::eSampleOffset3DU:
			return CombinedImageAccess::eTextureOffset3DU;
		case SampledImageAccess::eSampleOffset3DUBias:
			return CombinedImageAccess::eTextureOffset3DUBias;
		case SampledImageAccess::eSampleOffset2DRectU:
			return CombinedImageAccess::eTextureOffset2DRectU;
		case SampledImageAccess::eSampleOffset1DArrayU:
			return CombinedImageAccess::eTextureOffset1DArrayU;
		case SampledImageAccess::eSampleOffset1DArrayUBias:
			return CombinedImageAccess::eTextureOffset1DArrayUBias;
		case SampledImageAccess::eSampleOffset2DArrayU:
			return CombinedImageAccess::eTextureOffset2DArrayU;
		case SampledImageAccess::eSampleOffset2DArrayUBias:
			return CombinedImageAccess::eTextureOffset2DArrayUBias;
		case SampledImageAccess::eSampleProjOffset1DF2:
			return CombinedImageAccess::eTextureProjOffset1DF2;
		case SampledImageAccess::eSampleProjOffset1DF2Bias:
			return CombinedImageAccess::eTextureProjOffset1DF2Bias;
		case SampledImageAccess::eSampleProjOffset1DF4:
			return CombinedImageAccess::eTextureProjOffset1DF4;
		case SampledImageAccess::eSampleProjOffset1DF4Bias:
			return CombinedImageAccess::eTextureProjOffset1DF4Bias;
		case SampledImageAccess::eSampleProjOffset2DF3:
			return CombinedImageAccess::eTextureProjOffset2DF3;
		case SampledImageAccess::eSampleProjOffset2DF3Bias:
			return CombinedImageAccess::eTextureProjOffset2DF3Bias;
		case SampledImageAccess::eSampleProjOffset2DF4:
			return CombinedImageAccess::eTextureProjOffset2DF4;
		case SampledImageAccess::eSampleProjOffset2DF4Bias:
			return CombinedImageAccess::eTextureProjOffset2DF4Bias;
		case SampledImageAccess::eSampleProjOffset3DF:
			return CombinedImageAccess::eTextureProjOffset3DF;
		case SampledImageAccess::eSampleProjOffset3DFBias:
			return CombinedImageAccess::eTextureProjOffset3DFBias;
		case SampledImageAccess::eSampleProjOffset2DRectF3:
			return CombinedImageAccess::eTextureProjOffset2DRectF3;
		case SampledImageAccess::eSampleProjOffset2DRectF4:
			return CombinedImageAccess::eTextureProjOffset2DRectF4;
		case SampledImageAccess::eSampleProjOffset1DI2:
			return CombinedImageAccess::eTextureProjOffset1DI2;
		case SampledImageAccess::eSampleProjOffset1DI2Bias:
			return CombinedImageAccess::eTextureProjOffset1DI2Bias;
		case SampledImageAccess::eSampleProjOffset1DI4:
			return CombinedImageAccess::eTextureProjOffset1DI4;
		case SampledImageAccess::eSampleProjOffset1DI4Bias:
			return CombinedImageAccess::eTextureProjOffset1DI4Bias;
		case SampledImageAccess::eSampleProjOffset2DI3:
			return CombinedImageAccess::eTextureProjOffset2DI3;
		case SampledImageAccess::eSampleProjOffset2DI3Bias:
			return CombinedImageAccess::eTextureProjOffset2DI3Bias;
		case SampledImageAccess::eSampleProjOffset2DI4:
			return CombinedImageAccess::eTextureProjOffset2DI4;
		case SampledImageAccess::eSampleProjOffset2DI4Bias:
			return CombinedImageAccess::eTextureProjOffset2DI4Bias;
		case SampledImageAccess::eSampleProjOffset3DI:
			return CombinedImageAccess::eTextureProjOffset3DI;
		case SampledImageAccess::eSampleProjOffset3DIBias:
			return CombinedImageAccess::eTextureProjOffset3DIBias;
		case SampledImageAccess::eSampleProjOffset2DRectI3:
			return CombinedImageAccess::eTextureProjOffset2DRectI3;
		case SampledImageAccess::eSampleProjOffset2DRectI4:
			return CombinedImageAccess::eTextureProjOffset2DRectI4;
		case SampledImageAccess::eSampleProjOffset1DU2:
			return CombinedImageAccess::eTextureProjOffset1DU2;
		case SampledImageAccess::eSampleProjOffset1DU2Bias:
			return CombinedImageAccess::eTextureProjOffset1DU2Bias;
		case SampledImageAccess::eSampleProjOffset1DU4:
			return CombinedImageAccess::eTextureProjOffset1DU4;
		case SampledImageAccess::eSampleProjOffset1DU4Bias:
			return CombinedImageAccess::eTextureProjOffset1DU4Bias;
		case SampledImageAccess::eSampleProjOffset2DU3:
			return CombinedImageAccess::eTextureProjOffset2DU3;
		case SampledImageAccess::eSampleProjOffset2DU3Bias:
			return CombinedImageAccess::eTextureProjOffset2DU3Bias;
		case SampledImageAccess::eSampleProjOffset2DU4:
			return CombinedImageAccess::eTextureProjOffset2DU4;
		case SampledImageAccess::eSampleProjOffset2DU4Bias:
			return CombinedImageAccess::eTextureProjOffset2DU4Bias;
		case SampledImageAccess::eSampleProjOffset3DU:
			return CombinedImageAccess::eTextureProjOffset3DU;
		case SampledImageAccess::eSampleProjOffset3DUBias:
			return CombinedImageAccess::eTextureProjOffset3DUBias;
		case SampledImageAccess::eSampleProjOffset2DRectU3:
			return CombinedImageAccess::eTextureProjOffset2DRectU3;
		case SampledImageAccess::eSampleProjOffset2DRectU4:
			return CombinedImageAccess::eTextureProjOffset2DRectU4;
		case SampledImageAccess::eSampleLodOffset1DF:
			return CombinedImageAccess::eTextureLodOffset1DF;
		case SampledImageAccess::eSampleLodOffset2DF:
			return CombinedImageAccess::eTextureLodOffset2DF;
		case SampledImageAccess::eSampleLodOffset3DF:
			return CombinedImageAccess::eTextureLodOffset3DF;
		case SampledImageAccess::eSampleLodOffset1DArrayF:
			return CombinedImageAccess::eTextureLodOffset1DArrayF;
		case SampledImageAccess::eSampleLodOffset2DArrayF:
			return CombinedImageAccess::eTextureLodOffset2DArrayF;
		case SampledImageAccess::eSampleLodOffset1DI:
			return CombinedImageAccess::eTextureLodOffset1DI;
		case SampledImageAccess::eSampleLodOffset2DI:
			return CombinedImageAccess::eTextureLodOffset2DI;
		case SampledImageAccess::eSampleLodOffset3DI:
			return CombinedImageAccess::eTextureLodOffset3DI;
		case SampledImageAccess::eSampleLodOffset1DArrayI:
			return CombinedImageAccess::eTextureLodOffset1DArrayI;
		case SampledImageAccess::eSampleLodOffset2DArrayI:
			return CombinedImageAccess::eTextureLodOffset2DArrayI;
		case SampledImageAccess::eSampleLodOffset1DU:
			return CombinedImageAccess::eTextureLodOffset1DU;
		case SampledImageAccess::eSampleLodOffset2DU:
			return CombinedImageAccess::eTextureLodOffset2DU;
		case SampledImageAccess::eSampleLodOffset3DU:
			return CombinedImageAccess::eTextureLodOffset3DU;
		case SampledImageAccess::eSampleLodOffset1DArrayU:
			return CombinedImageAccess::eTextureLodOffset1DArrayU;
		case SampledImageAccess::eSampleLodOffset2DArrayU:
			return CombinedImageAccess::eTextureLodOffset2DArrayU;
		case SampledImageAccess::eSampleProjLod1DF2:
			return CombinedImageAccess::eTextureProjLod1DF2;
		case SampledImageAccess::eSampleProjLod1DF4:
			return CombinedImageAccess::eTextureProjLod1DF4;
		case SampledImageAccess::eSampleProjLod2DF3:
			return CombinedImageAccess::eTextureProjLod2DF3;
		case SampledImageAccess::eSampleProjLod2DF4:
			return CombinedImageAccess::eTextureProjLod2DF4;
		case SampledImageAccess::eSampleProjLod3DF:
			return CombinedImageAccess::eTextureProjLod3DF;
		case SampledImageAccess::eSampleProjLod1DI2:
			return CombinedImageAccess::eTextureProjLod1DI2;
		case SampledImageAccess::eSampleProjLod1DI4:
			return CombinedImageAccess::eTextureProjLod1DI4;
		case SampledImageAccess::eSampleProjLod2DI3:
			return CombinedImageAccess::eTextureProjLod2DI3;
		case SampledImageAccess::eSampleProjLod2DI4:
			return CombinedImageAccess::eTextureProjLod2DI4;
		case SampledImageAccess::eSampleProjLod3DI:
			return CombinedImageAccess::eTextureProjLod3DI;
		case SampledImageAccess::eSampleProjLod1DU2:
			return CombinedImageAccess::eTextureProjLod1DU2;
		case SampledImageAccess::eSampleProjLod1DU4:
			return CombinedImageAccess::eTextureProjLod1DU4;
		case SampledImageAccess::eSampleProjLod2DU3:
			return CombinedImageAccess::eTextureProjLod2DU3;
		case SampledImageAccess::eSampleProjLod2DU4:
			return CombinedImageAccess::eTextureProjLod2DU4;
		case SampledImageAccess::eSampleProjLod3DU:
			return CombinedImageAccess::eTextureProjLod3DU;
		case SampledImageAccess::eSampleProjLodOffset1DF2:
			return CombinedImageAccess::eTextureProjLodOffset1DF2;
		case SampledImageAccess::eSampleProjLodOffset1DF4:
			return CombinedImageAccess::eTextureProjLodOffset1DF4;
		case SampledImageAccess::eSampleProjLodOffset2DF3:
			return CombinedImageAccess::eTextureProjLodOffset2DF3;
		case SampledImageAccess::eSampleProjLodOffset2DF4:
			return CombinedImageAccess::eTextureProjLodOffset2DF4;
		case SampledImageAccess::eSampleProjLodOffset3DF:
			return CombinedImageAccess::eTextureProjLodOffset3DF;
		case SampledImageAccess::eSampleProjLodOffset1DI2:
			return CombinedImageAccess::eTextureProjLodOffset1DI2;
		case SampledImageAccess::eSampleProjLodOffset1DI4:
			return CombinedImageAccess::eTextureProjLodOffset1DI4;
		case SampledImageAccess::eSampleProjLodOffset2DI3:
			return CombinedImageAccess::eTextureProjLodOffset2DI3;
		case SampledImageAccess::eSampleProjLodOffset2DI4:
			return CombinedImageAccess::eTextureProjLodOffset2DI4;
		case SampledImageAccess::eSampleProjLodOffset3DI:
			return CombinedImageAccess::eTextureProjLodOffset3DI;
		case SampledImageAccess::eSampleProjLodOffset1DU2:
			return CombinedImageAccess::eTextureProjLodOffset1DU2;
		case SampledImageAccess::eSampleProjLodOffset1DU4:
			return CombinedImageAccess::eTextureProjLodOffset1DU4;
		case SampledImageAccess::eSampleProjLodOffset2DU3:
			return CombinedImageAccess::eTextureProjLodOffset2DU3;
		case SampledImageAccess::eSampleProjLodOffset2DU4:
			return CombinedImageAccess::eTextureProjLodOffset2DU4;
		case SampledImageAccess::eSampleProjLodOffset3DU:
			return CombinedImageAccess::eTextureProjLodOffset3DU;
		case SampledImageAccess::eSampleGrad1DF:
			return CombinedImageAccess::eTextureGrad1DF;
		case SampledImageAccess::eSampleGrad2DF:
			return CombinedImageAccess::eTextureGrad2DF;
		case SampledImageAccess::eSampleGrad3DF:
			return CombinedImageAccess::eTextureGrad3DF;
		case SampledImageAccess::eSampleGradCubeF:
			return CombinedImageAccess::eTextureGradCubeF;
		case SampledImageAccess::eSampleGrad2DRectF:
			return CombinedImageAccess::eTextureGrad2DRectF;
		case SampledImageAccess::eSampleGrad1DArrayF:
			return CombinedImageAccess::eTextureGrad1DArrayF;
		case SampledImageAccess::eSampleGrad2DArrayF:
			return CombinedImageAccess::eTextureGrad2DArrayF;
		case SampledImageAccess::eSampleGradCubeArrayF:
			return CombinedImageAccess::eTextureGradCubeArrayF;
		case SampledImageAccess::eSampleGrad1DI:
			return CombinedImageAccess::eTextureGrad1DI;
		case SampledImageAccess::eSampleGrad2DI:
			return CombinedImageAccess::eTextureGrad2DI;
		case SampledImageAccess::eSampleGrad3DI:
			return CombinedImageAccess::eTextureGrad3DI;
		case SampledImageAccess::eSampleGradCubeI:
			return CombinedImageAccess::eTextureGradCubeI;
		case SampledImageAccess::eSampleGrad2DRectI:
			return CombinedImageAccess::eTextureGrad2DRectI;
		case SampledImageAccess::eSampleGrad1DArrayI:
			return CombinedImageAccess::eTextureGrad1DArrayI;
		case SampledImageAccess::eSampleGrad2DArrayI:
			return CombinedImageAccess::eTextureGrad2DArrayI;
		case SampledImageAccess::eSampleGradCubeArrayI:
			return CombinedImageAccess::eTextureGradCubeArrayI;
		case SampledImageAccess::eSampleGrad1DU:
			return CombinedImageAccess::eTextureGrad1DU;
		case SampledImageAccess::eSampleGrad2DU:
			return CombinedImageAccess::eTextureGrad2DU;
		case SampledImageAccess::eSampleGrad3DU:
			return CombinedImageAccess::eTextureGrad3DU;
		case SampledImageAccess::eSampleGradCubeU:
			return CombinedImageAccess::eTextureGradCubeU;
		case SampledImageAccess::eSampleGrad2DRectU:
			return CombinedImageAccess::eTextureGrad2DRectU;
		case SampledImageAccess::eSampleGrad1DArrayU:
			return CombinedImageAccess::eTextureGrad1DArrayU;
		case SampledImageAccess::eSampleGrad2DArrayU:
			return CombinedImageAccess::eTextureGrad2DArrayU;
		case SampledImageAccess::eSampleGradCubeArrayU:
			return CombinedImageAccess::eTextureGradCubeArrayU;
		case SampledImageAccess::eSampleGradOffset1DF:
			return CombinedImageAccess::eTextureGradOffset1DF;
		case SampledImageAccess::eSampleGradOffset2DF:
			return CombinedImageAccess::eTextureGradOffset2DF;
		case SampledImageAccess::eSampleGradOffset3DF:
			return CombinedImageAccess::eTextureGradOffset3DF;
		case SampledImageAccess::eSampleGradOffset2DRectF:
			return CombinedImageAccess::eTextureGradOffset2DRectF;
		case SampledImageAccess::eSampleGradOffset1DArrayF:
			return CombinedImageAccess::eTextureGradOffset1DArrayF;
		case SampledImageAccess::eSampleGradOffset2DArrayF:
			return CombinedImageAccess::eTextureGradOffset2DArrayF;
		case SampledImageAccess::eSampleGradOffset1DI:
			return CombinedImageAccess::eTextureGradOffset1DI;
		case SampledImageAccess::eSampleGradOffset2DI:
			return CombinedImageAccess::eTextureGradOffset2DI;
		case SampledImageAccess::eSampleGradOffset3DI:
			return CombinedImageAccess::eTextureGradOffset3DI;
		case SampledImageAccess::eSampleGradOffset2DRectI:
			return CombinedImageAccess::eTextureGradOffset2DRectI;
		case SampledImageAccess::eSampleGradOffset1DArrayI:
			return CombinedImageAccess::eTextureGradOffset1DArrayI;
		case SampledImageAccess::eSampleGradOffset2DArrayI:
			return CombinedImageAccess::eTextureGradOffset2DArrayI;
		case SampledImageAccess::eSampleGradOffset1DU:
			return CombinedImageAccess::eTextureGradOffset1DU;
		case SampledImageAccess::eSampleGradOffset2DU:
			return CombinedImageAccess::eTextureGradOffset2DU;
		case SampledImageAccess::eSampleGradOffset3DU:
			return CombinedImageAccess::eTextureGradOffset3DU;
		case SampledImageAccess::eSampleGradOffset2DRectU:
			return CombinedImageAccess::eTextureGradOffset2DRectU;
		case SampledImageAccess::eSampleGradOffset1DArrayU:
			return CombinedImageAccess::eTextureGradOffset1DArrayU;
		case SampledImageAccess::eSampleGradOffset2DArrayU:
			return CombinedImageAccess::eTextureGradOffset2DArrayU;
		case SampledImageAccess::eSampleProjGrad1DF2:
			return CombinedImageAccess::eTextureProjGrad1DF2;
		case SampledImageAccess::eSampleProjGrad1DF4:
			return CombinedImageAccess::eTextureProjGrad1DF4;
		case SampledImageAccess::eSampleProjGrad2DF3:
			return CombinedImageAccess::eTextureProjGrad2DF3;
		case SampledImageAccess::eSampleProjGrad2DF4:
			return CombinedImageAccess::eTextureProjGrad2DF4;
		case SampledImageAccess::eSampleProjGrad3DF:
			return CombinedImageAccess::eTextureProjGrad3DF;
		case SampledImageAccess::eSampleProjGrad2DRectF3:
			return CombinedImageAccess::eTextureProjGrad2DRectF3;
		case SampledImageAccess::eSampleProjGrad2DRectF4:
			return CombinedImageAccess::eTextureProjGrad2DRectF4;
		case SampledImageAccess::eSampleProjGrad1DI2:
			return CombinedImageAccess::eTextureProjGrad1DI2;
		case SampledImageAccess::eSampleProjGrad1DI4:
			return CombinedImageAccess::eTextureProjGrad1DI4;
		case SampledImageAccess::eSampleProjGrad2DI3:
			return CombinedImageAccess::eTextureProjGrad2DI3;
		case SampledImageAccess::eSampleProjGrad2DI4:
			return CombinedImageAccess::eTextureProjGrad2DI4;
		case SampledImageAccess::eSampleProjGrad3DI:
			return CombinedImageAccess::eTextureProjGrad3DI;
		case SampledImageAccess::eSampleProjGrad2DRectI3:
			return CombinedImageAccess::eTextureProjGrad2DRectI3;
		case SampledImageAccess::eSampleProjGrad2DRectI4:
			return CombinedImageAccess::eTextureProjGrad2DRectI4;
		case SampledImageAccess::eSampleProjGrad1DU2:
			return CombinedImageAccess::eTextureProjGrad1DU2;
		case SampledImageAccess::eSampleProjGrad1DU4:
			return CombinedImageAccess::eTextureProjGrad1DU4;
		case SampledImageAccess::eSampleProjGrad2DU3:
			return CombinedImageAccess::eTextureProjGrad2DU3;
		case SampledImageAccess::eSampleProjGrad2DU4:
			return CombinedImageAccess::eTextureProjGrad2DU4;
		case SampledImageAccess::eSampleProjGrad3DU:
			return CombinedImageAccess::eTextureProjGrad3DU;
		case SampledImageAccess::eSampleProjGrad2DRectU3:
			return CombinedImageAccess::eTextureProjGrad2DRectU3;
		case SampledImageAccess::eSampleProjGrad2DRectU4:
			return CombinedImageAccess::eTextureProjGrad2DRectU4;
		case SampledImageAccess::eSampleProjGradOffset1DF2:
			return CombinedImageAccess::eTextureProjGradOffset1DF2;
		case SampledImageAccess::eSampleProjGradOffset1DF4:
			return CombinedImageAccess::eTextureProjGradOffset1DF4;
		case SampledImageAccess::eSampleProjGradOffset2DF3:
			return CombinedImageAccess::eTextureProjGradOffset2DF3;
		case SampledImageAccess::eSampleProjGradOffset2DF4:
			return CombinedImageAccess::eTextureProjGradOffset2DF4;
		case SampledImageAccess::eSampleProjGradOffset3DF:
			return CombinedImageAccess::eTextureProjGradOffset3DF;
		case SampledImageAccess::eSampleProjGradOffset2DRectF3:
			return CombinedImageAccess::eTextureProjGradOffset2DRectF3;
		case SampledImageAccess::eSampleProjGradOffset2DRectF4:
			return CombinedImageAccess::eTextureProjGradOffset2DRectF4;
		case SampledImageAccess::eSampleProjGradOffset1DI2:
			return CombinedImageAccess::eTextureProjGradOffset1DI2;
		case SampledImageAccess::eSampleProjGradOffset1DI4:
			return CombinedImageAccess::eTextureProjGradOffset1DI4;
		case SampledImageAccess::eSampleProjGradOffset2DI3:
			return CombinedImageAccess::eTextureProjGradOffset2DI3;
		case SampledImageAccess::eSampleProjGradOffset2DI4:
			return CombinedImageAccess::eTextureProjGradOffset2DI4;
		case SampledImageAccess::eSampleProjGradOffset3DI:
			return CombinedImageAccess::eTextureProjGradOffset3DI;
		case SampledImageAccess::eSampleProjGradOffset2DRectI3:
			return CombinedImageAccess::eTextureProjGradOffset2DRectI3;
		case SampledImageAccess::eSampleProjGradOffset2DRectI4:
			return CombinedImageAccess::eTextureProjGradOffset2DRectI4;
		case SampledImageAccess::eSampleProjGradOffset1DU2:
			return CombinedImageAccess::eTextureProjGradOffset1DU2;
		case SampledImageAccess::eSampleProjGradOffset1DU4:
			return CombinedImageAccess::eTextureProjGradOffset1DU4;
		case SampledImageAccess::eSampleProjGradOffset2DU3:
			return CombinedImageAccess::eTextureProjGradOffset2DU3;
		case SampledImageAccess::eSampleProjGradOffset2DU4:
			return CombinedImageAccess::eTextureProjGradOffset2DU4;
		case SampledImageAccess::eSampleProjGradOffset3DU:
			return CombinedImageAccess::eTextureProjGradOffset3DU;
		case SampledImageAccess::eSampleProjGradOffset2DRectU3:
			return CombinedImageAccess::eTextureProjGradOffset2DRectU3;
		case SampledImageAccess::eSampleProjGradOffset2DRectU4:
			return CombinedImageAccess::eTextureProjGradOffset2DRectU4;
		case SampledImageAccess::eSample1DShadowF:
			return CombinedImageAccess::eTexture1DShadowF;
		case SampledImageAccess::eSample1DShadowFBias:
			return CombinedImageAccess::eTexture1DShadowFBias;
		case SampledImageAccess::eSample2DShadowF:
			return CombinedImageAccess::eTexture2DShadowF;
		case SampledImageAccess::eSample2DShadowFBias:
			return CombinedImageAccess::eTexture2DShadowFBias;
		case SampledImageAccess::eSampleCubeShadowF:
			return CombinedImageAccess::eTextureCubeShadowF;
		case SampledImageAccess::eSampleCubeShadowFBias:
			return CombinedImageAccess::eTextureCubeShadowFBias;
		case SampledImageAccess::eSample1DArrayShadowF:
			return CombinedImageAccess::eTexture1DArrayShadowF;
		case SampledImageAccess::eSample1DArrayShadowFBias:
			return CombinedImageAccess::eTexture1DArrayShadowFBias;
		case SampledImageAccess::eSample2DArrayShadowF:
			return CombinedImageAccess::eTexture2DArrayShadowF;
		case SampledImageAccess::eSample2DRectShadowF:
			return CombinedImageAccess::eTexture2DRectShadowF;
		case SampledImageAccess::eSampleCubeArrayShadowF:
			return CombinedImageAccess::eTextureCubeArrayShadowF;
		case SampledImageAccess::eSampleProj1DShadowF:
			return CombinedImageAccess::eTextureProj1DShadowF;
		case SampledImageAccess::eSampleProj1DShadowFBias:
			return CombinedImageAccess::eTextureProj1DShadowFBias;
		case SampledImageAccess::eSampleProj2DShadowF:
			return CombinedImageAccess::eTextureProj2DShadowF;
		case SampledImageAccess::eSampleProj2DShadowFBias:
			return CombinedImageAccess::eTextureProj2DShadowFBias;
		case SampledImageAccess::eSampleProj2DRectShadowF:
			return CombinedImageAccess::eTextureProj2DRectShadowF;
		case SampledImageAccess::eSampleLod1DShadowF:
			return CombinedImageAccess::eTextureLod1DShadowF;
		case SampledImageAccess::eSampleLod2DShadowF:
			return CombinedImageAccess::eTextureLod2DShadowF;
		case SampledImageAccess::eSampleLod1DArrayShadowF:
			return CombinedImageAccess::eTextureLod1DArrayShadowF;
		case SampledImageAccess::eSampleOffset2DRectShadowF:
			return CombinedImageAccess::eTextureOffset2DRectShadowF;
		case SampledImageAccess::eSampleOffset1DShadowF:
			return CombinedImageAccess::eTextureOffset1DShadowF;
		case SampledImageAccess::eSampleOffset1DShadowFBias:
			return CombinedImageAccess::eTextureOffset1DShadowFBias;
		case SampledImageAccess::eSampleOffset2DShadowF:
			return CombinedImageAccess::eTextureOffset2DShadowF;
		case SampledImageAccess::eSampleOffset2DShadowFBias:
			return CombinedImageAccess::eTextureOffset2DShadowFBias;
		case SampledImageAccess::eSampleOffset1DArrayShadowF:
			return CombinedImageAccess::eTextureOffset1DArrayShadowF;
		case SampledImageAccess::eSampleOffset2DArrayShadowF:
			return CombinedImageAccess::eTextureOffset2DArrayShadowF;
		case SampledImageAccess::eSampleProjOffset1DShadowF:
			return CombinedImageAccess::eTextureProjOffset1DShadowF;
		case SampledImageAccess::eSampleProjOffset1DShadowFBias:
			return CombinedImageAccess::eTextureProjOffset1DShadowFBias;
		case SampledImageAccess::eSampleProjOffset2DShadowF:
			return CombinedImageAccess::eTextureProjOffset2DShadowF;
		case SampledImageAccess::eSampleProjOffset2DShadowFBias:
			return CombinedImageAccess::eTextureProjOffset2DShadowFBias;
		case SampledImageAccess::eSampleProjOffset2DRectShadowF:
			return CombinedImageAccess::eTextureProjOffset2DRectShadowF;
		case SampledImageAccess::eSampleLodOffset1DShadowF:
			return CombinedImageAccess::eTextureLodOffset1DShadowF;
		case SampledImageAccess::eSampleLodOffset2DShadowF:
			return CombinedImageAccess::eTextureLodOffset2DShadowF;
		case SampledImageAccess::eSampleLodOffset1DArrayShadowF:
			return CombinedImageAccess::eTextureLodOffset1DArrayShadowF;
		case SampledImageAccess::eSampleProjLod1DShadowF:
			return CombinedImageAccess::eTextureProjLod1DShadowF;
		case SampledImageAccess::eSampleProjLod2DShadowF:
			return CombinedImageAccess::eTextureProjLod2DShadowF;
		case SampledImageAccess::eSampleProjLodOffset1DShadowF:
			return CombinedImageAccess::eTextureProjLodOffset1DShadowF;
		case SampledImageAccess::eSampleProjLodOffset2DShadowF:
			return CombinedImageAccess::eTextureProjLodOffset2DShadowF;
		case SampledImageAccess::eSampleGrad2DRectShadowF:
			return CombinedImageAccess::eTextureGrad2DRectShadowF;
		case SampledImageAccess::eSampleGrad1DShadowF:
			return CombinedImageAccess::eTextureGrad1DShadowF;
		case SampledImageAccess::eSampleGrad2DShadowF:
			return CombinedImageAccess::eTextureGrad2DShadowF;
		case SampledImageAccess::eSampleGrad1DArrayShadowF:
			return CombinedImageAccess::eTextureGrad1DArrayShadowF;
		case SampledImageAccess::eSampleGradOffset2DRectShadowF:
			return CombinedImageAccess::eTextureGradOffset2DRectShadowF;
		case SampledImageAccess::eSampleGradOffset1DShadowF:
			return CombinedImageAccess::eTextureGradOffset1DShadowF;
		case SampledImageAccess::eSampleGradOffset2DShadowF:
			return CombinedImageAccess::eTextureGradOffset2DShadowF;
		case SampledImageAccess::eSampleGradOffset1DArrayShadowF:
			return CombinedImageAccess::eTextureGradOffset1DArrayShadowF;
		case SampledImageAccess::eSampleGradOffset2DArrayShadowF:
			return CombinedImageAccess::eTextureGradOffset2DArrayShadowF;
		case SampledImageAccess::eSampleProjGrad1DShadowF:
			return CombinedImageAccess::eTextureProjGrad1DShadowF;
		case SampledImageAccess::eSampleProjGrad2DShadowF:
			return CombinedImageAccess::eTextureProjGrad2DShadowF;
		case SampledImageAccess::eSampleProjGrad2DRectShadowF:
			return CombinedImageAccess::eTextureProjGrad2DRectShadowF;
		case SampledImageAccess::eSampleProjGradOffset1DShadowF:
			return CombinedImageAccess::eTextureProjGradOffset1DShadowF;
		case SampledImageAccess::eSampleProjGradOffset2DShadowF:
			return CombinedImageAccess::eTextureProjGradOffset2DShadowF;
		case SampledImageAccess::eSampleProjGradOffset2DRectShadowF:
			return CombinedImageAccess::eTextureProjGradOffset2DRectShadowF;
		case SampledImageAccess::eSampleGather2DF:
			return CombinedImageAccess::eTextureGather2DF;
		case SampledImageAccess::eSampleGather2DArrayF:
			return CombinedImageAccess::eTextureGather2DArrayF;
		case SampledImageAccess::eSampleGatherCubeF:
			return CombinedImageAccess::eTextureGatherCubeF;
		case SampledImageAccess::eSampleGatherCubeArrayF:
			return CombinedImageAccess::eTextureGatherCubeArrayF;
		case SampledImageAccess::eSampleGather2DRectF:
			return CombinedImageAccess::eTextureGather2DRectF;
		case SampledImageAccess::eSampleGather2DI:
			return CombinedImageAccess::eTextureGather2DI;
		case SampledImageAccess::eSampleGather2DArrayI:
			return CombinedImageAccess::eTextureGather2DArrayI;
		case SampledImageAccess::eSampleGatherCubeI:
			return CombinedImageAccess::eTextureGatherCubeI;
		case SampledImageAccess::eSampleGatherCubeArrayI:
			return CombinedImageAccess::eTextureGatherCubeArrayI;
		case SampledImageAccess::eSampleGather2DRectI:
			return CombinedImageAccess::eTextureGather2DRectI;
		case SampledImageAccess::eSampleGather2DU:
			return CombinedImageAccess::eTextureGather2DU;
		case SampledImageAccess::eSampleGather2DArrayU:
			return CombinedImageAccess::eTextureGather2DArrayU;
		case SampledImageAccess::eSampleGatherCubeU:
			return CombinedImageAccess::eTextureGatherCubeU;
		case SampledImageAccess::eSampleGatherCubeArrayU:
			return CombinedImageAccess::eTextureGatherCubeArrayU;
		case SampledImageAccess::eSampleGather2DRectU:
			return CombinedImageAccess::eTextureGather2DRectU;
		case SampledImageAccess::eSampleGatherOffset2DF:
			return CombinedImageAccess::eTextureGatherOffset2DF;
		case SampledImageAccess::eSampleGatherOffset2DArrayF:
			return CombinedImageAccess::eTextureGatherOffset2DArrayF;
		case SampledImageAccess::eSampleGatherOffset2DRectF:
			return CombinedImageAccess::eTextureGatherOffset2DRectF;
		case SampledImageAccess::eSampleGatherOffset2DI:
			return CombinedImageAccess::eTextureGatherOffset2DI;
		case SampledImageAccess::eSampleGatherOffset2DArrayI:
			return CombinedImageAccess::eTextureGatherOffset2DArrayI;
		case SampledImageAccess::eSampleGatherOffset2DRectI:
			return CombinedImageAccess::eTextureGatherOffset2DRectI;
		case SampledImageAccess::eSampleGatherOffset2DU:
			return CombinedImageAccess::eTextureGatherOffset2DU;
		case SampledImageAccess::eSampleGatherOffset2DArrayU:
			return CombinedImageAccess::eTextureGatherOffset2DArrayU;
		case SampledImageAccess::eSampleGatherOffset2DRectU:
			return CombinedImageAccess::eTextureGatherOffset2DRectU;
		case SampledImageAccess::eSampleGatherOffsets2DF:
			return CombinedImageAccess::eTextureGatherOffsets2DF;
		case SampledImageAccess::eSampleGatherOffsets2DArrayF:
			return CombinedImageAccess::eTextureGatherOffsets2DArrayF;
		case SampledImageAccess::eSampleGatherOffsets2DRectF:
			return CombinedImageAccess::eTextureGatherOffsets2DRectF;
		case SampledImageAccess::eSampleGatherOffsets2DI:
			return CombinedImageAccess::eTextureGatherOffsets2DI;
		case SampledImageAccess::eSampleGatherOffsets2DArrayI:
			return CombinedImageAccess::eTextureGatherOffsets2DArrayI;
		case SampledImageAccess::eSampleGatherOffsets2DRectI:
			return CombinedImageAccess::eTextureGatherOffsets2DRectI;
		case SampledImageAccess::eSampleGatherOffsets2DU:
			return CombinedImageAccess::eTextureGatherOffsets2DU;
		case SampledImageAccess::eSampleGatherOffsets2DArrayU:
			return CombinedImageAccess::eTextureGatherOffsets2DArrayU;
		case SampledImageAccess::eSampleGatherOffsets2DRectU:
			return CombinedImageAccess::eTextureGatherOffsets2DRectU;
		case SampledImageAccess::eSampleGather2DShadowF:
			return CombinedImageAccess::eTextureGather2DShadowF;
		case SampledImageAccess::eSampleGather2DArrayShadowF:
			return CombinedImageAccess::eTextureGather2DArrayShadowF;
		case SampledImageAccess::eSampleGatherCubeShadowF:
			return CombinedImageAccess::eTextureGatherCubeShadowF;
		case SampledImageAccess::eSampleGatherCubeArrayShadowF:
			return CombinedImageAccess::eTextureGatherCubeArrayShadowF;
		case SampledImageAccess::eSampleGather2DRectShadowF:
			return CombinedImageAccess::eTextureGather2DRectShadowF;
		case SampledImageAccess::eSampleGatherOffset2DShadowF:
			return CombinedImageAccess::eTextureGatherOffset2DShadowF;
		case SampledImageAccess::eSampleGatherOffset2DArrayShadowF:
			return CombinedImageAccess::eTextureGatherOffset2DArrayShadowF;
		case SampledImageAccess::eSampleGatherOffset2DRectShadowF:
			return CombinedImageAccess::eTextureGatherOffset2DRectShadowF;
		case SampledImageAccess::eSampleGatherOffsets2DShadowF:
			return CombinedImageAccess::eTextureGatherOffsets2DShadowF;
		case SampledImageAccess::eSampleGatherOffsets2DArrayShadowF:
			return CombinedImageAccess::eTextureGatherOffsets2DArrayShadowF;
		case SampledImageAccess::eSampleGatherOffsets2DRectShadowF:
			return CombinedImageAccess::eTextureGatherOffsets2DRectShadowF;
		case SampledImageAccess::eCount:
			return CombinedImageAccess::eCount;
		case SampledImageAccess::eInvalid:
			return CombinedImageAccess::eInvalid;
		default:
			AST_Failure( "Unsupported SampledImageAccess" );
			return CombinedImageAccess::eInvalid;
		}
	}

	//*********************************************************************************************
}
