/*
See LICENSE file in root folder
*/
#include "ShaderWriter/BaseTypes/Float.hpp"

namespace
{
	void compileFloat()
	{
		bool ignore;
		auto a = 0.0_f;
		auto b = 1.0_f;
		a += b;
		a -= b;
		a *= b;
		a /= b;
		ignore = a == b;
		ignore = a != b;
		ignore = a <= b;
		ignore = a >= b;
		ignore = a < b;
		ignore = a > b;
		a + b;
		a - b;
		a * b;
		a / b;
		a += 1.0f;
		a -= 1.0f;
		a *= 1.0f;
		a /= 1.0f;
		ignore = a == 1.0f;
		ignore = a != 1.0f;
		ignore = a <= 1.0f;
		ignore = a >= 1.0f;
		ignore = a < 1.0f;
		ignore = a > 1.0f;
		a + 1.0f;
		a - 1.0f;
		a * 1.0f;
		a / 1.0f;
		ignore = 1.0f == a;
		ignore = 1.0f != a;
		ignore = 1.0f <= a;
		ignore = 1.0f >= a;
		ignore = 1.0f < a;
		ignore = 1.0f > a;
		1.0f + a;
		1.0f - a;
		1.0f * a;
		1.0f / a;

		auto c = sdw::Optional< sdw::Float >{ b, false };
		a += c;
		a -= c;
		a *= c;
		a /= c;
		ignore = a == c;
		ignore = a != c;
		ignore = a <= c;
		ignore = a >= c;
		ignore = a < c;
		ignore = a > c;
		a + c;
		a - c;
		a * c;
		a / c;
		c += b;
		c -= b;
		c *= b;
		c /= b;
		ignore = c == b;
		ignore = c != b;
		ignore = c <= b;
		ignore = c >= b;
		ignore = c < b;
		ignore = c > b;
		c + b;
		c - b;
		c * b;
		c / b;
		c += 1.0f;
		c -= 1.0f;
		c *= 1.0f;
		c /= 1.0f;
		ignore = c == 1.0f;
		ignore = c != 1.0f;
		ignore = c <= 1.0f;
		ignore = c >= 1.0f;
		ignore = c < 1.0f;
		ignore = c > 1.0f;
		c + 1.0f;
		c - 1.0f;
		c * 1.0f;
		c / 1.0f;
		ignore = 1.0f == c;
		ignore = 1.0f != c;
		ignore = 1.0f <= c;
		ignore = 1.0f >= c;
		ignore = 1.0f < c;
		ignore = 1.0f > c;
		1.0f + c;
		1.0f - c;
		1.0f * c;
		1.0f / c;

		auto d = sdw::Optional< sdw::Float >{ b, false };
		a += d;
		a -= d;
		a *= d;
		a /= d;
		ignore = a == d;
		ignore = a != d;
		ignore = a <= d;
		ignore = a >= d;
		ignore = a < d;
		ignore = a > d;
		a + d;
		a - d;
		a * d;
		a / d;
		d += b;
		d -= b;
		d *= b;
		d /= b;
		ignore = d == b;
		ignore = d != b;
		ignore = d <= b;
		ignore = d >= b;
		ignore = d < b;
		ignore = d > b;
		d + b;
		d - b;
		d * b;
		d / b;
		d += 1.0f;
		d -= 1.0f;
		d *= 1.0f;
		d /= 1.0f;
		ignore = d == 1.0f;
		ignore = d != 1.0f;
		ignore = d <= 1.0f;
		ignore = d >= 1.0f;
		ignore = d < 1.0f;
		ignore = d > 1.0f;
		d + 1.0f;
		d - 1.0f;
		d * 1.0f;
		d / 1.0f;
		ignore = 1.0f == d;
		ignore = 1.0f != d;
		ignore = 1.0f <= d;
		ignore = 1.0f >= d;
		ignore = 1.0f < d;
		ignore = 1.0f > d;
		1.0f + d;
		1.0f - d;
		1.0f * d;
		1.0f / d;

		auto e = sdw::MaybeOptional< sdw::Float >{ c };
		a += e;
		a -= e;
		a *= e;
		a /= e;
		ignore = a == e;
		ignore = a != e;
		ignore = a <= e;
		ignore = a >= e;
		ignore = a < e;
		ignore = a > e;
		a + e;
		a - e;
		a * e;
		a / e;
		e += b;
		e -= b;
		e *= b;
		e /= b;
		ignore = e == b;
		ignore = e != b;
		ignore = e <= b;
		ignore = e >= b;
		ignore = e < b;
		ignore = e > b;
		e + b;
		e - b;
		e * b;
		e / b;
		e += 1.0f;
		e -= 1.0f;
		e *= 1.0f;
		e /= 1.0f;
		ignore = e == 1.0f;
		ignore = e != 1.0f;
		ignore = e <= 1.0f;
		ignore = e >= 1.0f;
		ignore = e < 1.0f;
		ignore = e > 1.0f;
		e + 1.0f;
		e - 1.0f;
		e * 1.0f;
		e / 1.0f;
		ignore = 1.0f == e;
		ignore = 1.0f != e;
		ignore = 1.0f <= e;
		ignore = 1.0f >= e;
		ignore = 1.0f < e;
		ignore = 1.0f > e;
		1.0f + e;
		1.0f - e;
		1.0f * e;
		1.0f / e;

		auto f = sdw::MaybeOptional< sdw::Float >{ b };
		a += f;
		a -= f;
		a *= f;
		a /= f;
		ignore = a == f;
		ignore = a != f;
		ignore = a <= f;
		ignore = a >= f;
		ignore = a < f;
		ignore = a > f;
		a + f;
		a - f;
		a * f;
		a / f;
		f += b;
		f -= b;
		f *= b;
		f /= b;
		ignore = f == b;
		ignore = f != b;
		ignore = f <= b;
		ignore = f >= b;
		ignore = f < b;
		ignore = f > b;
		f + b;
		f - b;
		f * b;
		f / b;
		f += 1.0f;
		f -= 1.0f;
		f *= 1.0f;
		f /= 1.0f;
		ignore = f == 1.0f;
		ignore = f != 1.0f;
		ignore = f <= 1.0f;
		ignore = f >= 1.0f;
		ignore = f < 1.0f;
		ignore = f > 1.0f;
		f + 1.0f;
		f - 1.0f;
		f * 1.0f;
		f / 1.0f;
		ignore = 1.0f == f;
		ignore = 1.0f != f;
		ignore = 1.0f <= f;
		ignore = 1.0f >= f;
		ignore = 1.0f < f;
		ignore = 1.0f > f;
		1.0f + f;
		1.0f - f;
		1.0f * f;
		1.0f / f;
	}
}
